version: '3.8'

services:
  abpcachingplayground-web:
    image: mycompanyname/abpcachingplayground-web:latest
    container_name: abpcachingplayground-web
    hostname: abpcachingplayground-web
    build:
      context: ../../
      dockerfile: src/AbpCachingPlayground.Web/Dockerfile.local
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80;
      - Kestrel__Certificates__Default__Path=/root/certificate/localhost.pfx
      - Kestrel__Certificates__Default__Password=9ab04747-6430-42d9-a539-73c3ba57a9c3
      - App__SelfUrl=https://localhost:44353
      - AuthServer__RequireHttpsMetadata=false
      - AuthServer__IsOnK8s=true
      - AuthServer__Authority=https://localhost:44347/
      - RemoteServices__Default__BaseUrl=http://abpcachingplayground-api
      - RemoteServices__AbpAccountPublic__BaseUrl=http://abpcachingplayground-authserver      
      - AuthServer__MetaAddress=http://abpcachingplayground-authserver
      - Redis__Configuration=redis
    ports:
      - "44353:443"
    depends_on:
      - abpcachingplayground-api
    restart: on-failure
    volumes:
      - ./certs:/root/certificate
    networks:
      - abp-network

  abpcachingplayground-api:
    image: mycompanyname/abpcachingplayground-api:latest
    container_name: abpcachingplayground-api
    hostname: abpcachingplayground-api
    build:
      context: ../../
      dockerfile: src/AbpCachingPlayground.HttpApi.Host/Dockerfile.local
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80;
      - Kestrel__Certificates__Default__Path=/root/certificate/localhost.pfx
      - Kestrel__Certificates__Default__Password=9ab04747-6430-42d9-a539-73c3ba57a9c3
      - App__SelfUrl=https://localhost:44372
      - App__HealthCheckUrl=http://abpcachingplayground-api/health-status
      - AuthServer__RequireHttpsMetadata=false
      - AuthServer__Authority=http://abpcachingplayground-authserver
      - AuthServer__MetaAddress=https://localhost:44347
      - ConnectionStrings__Default=Data Source=sql-server;Initial Catalog=AbpCachingPlayground;User Id=sa;Password=myPassw0rd;MultipleActiveResultSets=true;TrustServerCertificate=True;
      - Redis__Configuration=redis
    ports:
      - "44354:443"    
    depends_on:
      sql-server:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: on-failure
    volumes:
      - ./certs:/root/certificate
    networks:
      - abp-network
  
  abpcachingplayground-authserver:
    image: mycompanyname/abpcachingplayground-authserver:latest
    container_name: abpcachingplayground-authserver
    build:
      context: ../../
      dockerfile: src/AbpCachingPlayground.AuthServer/Dockerfile.local
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80;
      - App__SelfUrl=https://localhost:44347
      - App__CorsOrigins=https://localhost:44353,https://localhost:44372
      - App__RedirectAllowedUrls=https://localhost:44353,https://localhost:44372
      - AuthServer__RequireHttpsMetadata=false
      - AuthServer__Authority=https://localhost:44347
      - Kestrel__Certificates__Default__Path=/root/certificate/localhost.pfx
      - Kestrel__Certificates__Default__Password=9ab04747-6430-42d9-a539-73c3ba57a9c3
      - ConnectionStrings__Default=Data Source=sql-server;Initial Catalog=AbpCachingPlayground;User Id=sa;Password=myPassw0rd;MultipleActiveResultSets=true;TrustServerCertificate=True;
      - Redis__Configuration=redis
    ports:
      - "44334:443"
    depends_on:
      sql-server:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: on-failure
    volumes:
      - ./certs:/root/certificate
    networks:
      - abp-network

  
  db-migrator:
    image: mycompanyname/abpcachingplayground-db-migrator:latest
    container_name: db-migrator
    build:
      context: ../../
      dockerfile: src/AbpCachingPlayground.DbMigrator/Dockerfile.local
    environment:
      - OpenIddict__Applications__AbpCachingPlayground_Web__RootUrl=https://localhost:44353
      - OpenIddict__Applications__AbpCachingPlayground_Swagger__RootUrl=https://localhost:44372      
      - ConnectionStrings__Default=Data Source=sql-server;Initial Catalog=AbpCachingPlayground;User Id=sa;Password=myPassw0rd;MultipleActiveResultSets=true;TrustServerCertificate=True;
      - Redis__Configuration=redis
    restart: on-failure
    depends_on:
      sql-server:
        condition: service_healthy
    networks:
      - abp-network
  
  sql-server:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1434:1433"
    environment:
      SA_PASSWORD: "myPassw0rd"
      ACCEPT_EULA: "Y"
    volumes:
      - sqldata:/var/opt/mssql
    networks:
      - abp-network
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S sql-server -U sa -P "myPassw0rd" -Q "SELECT 1" -b -o /dev/null
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - abp-network
    healthcheck:
      test: ["CMD", "redis-cli","ping"]

volumes:
  sqldata:
    name: abpcachingplayground_sqldata
networks:
  abp-network:
    name: abpcachingplayground-network
    driver: bridge