using AbpCachingPlayground.EntityFrameworkCore;
using Xunit;

namespace AbpCachingPlayground.EntityFrameworkCore;

public class AbpCachingPlaygroundEntityFrameworkCoreCollectionFixtureBase : ICollectionFixture<AbpCachingPlaygroundEntityFrameworkCoreFixture>
{

}
